on: [push]

name: Deploy in Azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:app"
        push: true
        tags: gk13081987/testdeploy2:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapp-deployv2'
        publish-profile: ${{ secrets.azureWebAppPublishProfiles }}
        images: 'gk13081987/testdeploy2:${{ github.sha }}'